x-gpu-config:
  &gpu-config
  runtime: nvidia
  env_file: .env.gpu

services:

  rosbot:
    image: husarion/rosbot-gazebo:humble-0.13.0-20240115
    <<: *gpu-config
    network_mode: host 
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=10
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
       ros2 launch rosbot_gazebo simulation.launch.py
        mecanum:=${MECANUM:-True}
        namespace:=${ROBOT_NAMESPACE}
