x-gpu-config:
  &gpu-config
  #  runtime: nvidia
  env_file: .env.gpu

services:

  navigation:
    image: husarion/navigation2:humble-1.1.12-20240123
    <<: *gpu-config
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps
    environment:
      - ROBOT_NAMESPACE=${ROBOT_NAMESPACE}
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=10
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch /husarion_utils/bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/params.yaml
        map:=/maps/map.yaml
        use_sim_time:=True

